### ISSUE TITLE
Add the ability to cast to Google devices/speakers

### ISSUE THREAD

**Issue by DrDagless** [jeffvli/feishin#256]
## What do you want to be added?

Pretty much as the title states. I think this was on the roadmap for Sonixd at some point, but it would definitely be a killer feature. Not sure how technically feasible it is, so my apologies if it's out of scope.

## Additional context

Nothing else! Brilliant app!

**Comment by gulabbisht** [comment]
+1 on this!

**Comment by SeeDborg** [comment]
+1 too !

**Comment by kgarner7** [comment]
While this is clearly a wanted feature, I will note that at least actually implementing it requires actually owning a chromecast-compatible device. I don't know about @jeffvli, but I certainly do not have any so the likelihood this feature would be implemented is low

**Comment by graham2071** [comment]
You can use the docker version (not desktop) of feishin and use the cast feature of your browser.
One possible way is to create a docker compose file with navidrome and feishin services:

```yaml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    [the rest of your navidrome config]

  feishin:
    image: ghcr.io/jeffvli/feishin:latest
    ports:
      - "9180:9180"

```

Then open <http://localhost:9180> and connect to your navidrome server (the URL will be in this example: `http://navidrome:4533`)
