### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by felipemarinho97** [jeffvli/feishin#545]
## What do you want to be added?

When using the `SERVER_LOCK=true` would be nice to the user be redirected to a login page. Or at least a login prompt with just usename and password fields. The current behaviour Open Menu -> Manage Servers -> Add Server -> Login is counterintuitive.

**Comment by hhenne1** [comment]
not sure if this is the appropriate place to ask (sry), but i assume env variables to predetermine login data for the docker image is currently not a thing?

**Comment by kgarner7** [comment]
> not sure if this is the appropriate place to ask (sry), but i assume env variables to predetermine login data for the docker image is currently not a thing?

It isn't the best place (that'd _probably_ be discussion), but yes, they are absolutely supported in Docker. The following just worked for me
```yaml
services:
    feishin:
        container_name: feishin
        image: ghcr.io/jeffvli/feishin:latest
        restart: unless-stopped
        ports:
            - 9180:9180
        environment:
            - SERVER_NAME=jellyfin # pre defined server name
            - SERVER_LOCK=true # When true AND name/type/url are set, only username/password can be toggled
            - SERVER_TYPE=jellyfin # navidrome also works
            - SERVER_URL=http://address:port
```
