### ISSUE TITLE
[Feature request] Add option to increase height of the track progress bar

### ISSUE THREAD

**Issue by xusiai** [jeffvli/feishin#824]
### What do you want to be added?

An option to increase the height of the progress bar.

### Additional context

I often miss-click when I want to navigate track progress as the bar is rather small on high resolutions. An option to increase its height would be appreciated. 

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
This is too niche of a use case for a new option.

I recommend you to use the `Custom css` feature under `Advanced` tab in the settings page and just override the css on the sliders.


#### If you want both player and volume sliders
```css
#player-bar .mantine-Slider-track {
     height: 1rem;
}
```

#### If you only want the player slider
```css
#player-bar > div > div > div > div > div > div > div:first-child .mantine-Slider-track {
     height:1rem;
}
```
