### ISSUE TITLE
Custom css sanitizes variables

### ISSUE THREAD

**Issue by BANanaD3V** [jeffvli/feishin#851]
### Expected Behavior

Custom css should keep variables inside of :root

### Current Behavior

Custom css field removes css variables in root that stops me from theming feishin

### Steps to Reproduce

1. Go to custom css
2. Paste something containing variables, for example:
```css

:root {
    --secondary-color: #ff7878;
    --success-color: green;
    --warning-color: orange;
    --danger-color: #cc3232;
    --generic-border-color: #3232324d;
    --main-bg: #1e1e2e;
    --main-bg-transparent: 21,18,18;
    --main-fg: #e1e1e1;
    --main-fg-secondary: #969696;
    --window-bar-bg: #101010;
    --window-bar-fg: #fff;
}
```
3. Preview removes variables, saving also removes them

### Possible Solution

Do not remove variables

### Context

Can't theme feishin

### Application version

0.11.1

### Operating System and version

NixOS 24.11, Electron app

### Server and Version

Navidrome 0.53.3
